#!/bin/sh

DST_USER="$1"

cd ~
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/Standfestgit/bash-scripts.git
cp bash-scripts/standfest.zsh-theme .oh-my-zsh/themes
#sudo chsh -s /usr/bin/zsh ${DST_USER}
#zsh
